version: '3'

volumes:
  mongo_primary_data:
    driver: local

services:
  mongodb-primary:
    image: mongo:latest
    container_name: mongodb-primary
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_primary_data:/data/db
      - ./mongo/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
    ports:
      - '27017:27017'
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile=/data/keyfile/mongo-keyfile" ]

  mongodb-secondary:
    image: mongo:latest
    container_name: mongodb-secondary
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile=/data/keyfile/mongo-keyfile" ]

  mongodb-arbiter:
    image: mongo:latest
    container_name: mongodb-arbiter
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile=/data/keyfile/mongo-keyfile" ]
