volumes:
  mongo_primary_data:
    driver: local

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    depends_on:
      - auth
      - event
    environment:
      - PORT=8000
      - AUTH_SERVICE_HOST=auth
      - AUTH_SERVICE_PORT=8001
      - EVENT_SERVICE_HOST=event
      - EVENT_SERVICE_PORT=8002
      - JWT_SECRET=nexonEventManagementPlaform05161708
    ports:
      - '8000:8000'

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    depends_on:
      - mongodb-primary
    environment:
      - AUTH_SERVICE_HOST=auth
      - AUTH_SERVICE_PORT=8001
      - MONGODB_URI=mongodb://user1:password@mongodb-primary:27017/devdb?directConnection=true
      - JWT_SECRET=nexonEventManagementPlaform05161708
      - JWT_ACCESS_EXPIRATION_TIME=7d
      - JWT_REFRESH_EXPIRATION_TIME=14d
      - NODE_OPTIONS=--dns-result-order=ipv4first
    ports:
      - '8001:8001'

  event:
    container_name: event
    build:
      context: .
      dockerfile: ./apps/event/Dockerfile
    depends_on:
      - mongodb-primary
    environment:
      - EVENT_SERVICE_HOST=event
      - EVENT_SERVICE_PORT=8002
      - MONGODB_URI=mongodb://user1:password@mongodb-primary:27017/devdb?directConnection=true
      - NODE_OPTIONS=--dns-result-order=ipv4first
    env_file:
      - ./apps/event/.env
    ports:
      - '8002:8002'

  mongodb-primary:
    image: mongo:latest
    container_name: mongodb-primary
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=devdb
    volumes:
      - mongo_primary_data:/data/db
      - ./mongo/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27017:27017'
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile=/data/keyfile/mongo-keyfile" ]

  mongodb-secondary:
    image: mongo:latest
    container_name: mongodb-secondary
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile=/data/keyfile/mongo-keyfile" ]

  mongodb-arbiter:
    image: mongo:latest
    container_name: mongodb-arbiter
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo/mongo-keyfile:/data/keyfile/mongo-keyfile:ro
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile=/data/keyfile/mongo-keyfile" ]
